name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch :
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context:  files .
          file: ./Dockerfile
          push: true
          tags: |
            afcarvalho1991/cmdbuild:om-2.3-3.4.1-d
            afcarvalho1991/cmdbuild:latest

      - name: Deploy with Docker Compose
        run: |
          docker compose up -d
          
